# Generated by Django 3.2.7 on 2021-09-24 08:59

from django.db import migrations, models
import payapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Цена')),
                ('image', models.ImageField(upload_to=payapp.models.user_directory_path, verbose_name='Постер')),
            ],
        ),
    ]
